/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ClassConsensus__factory } from "./ClassConsensus__factory";
export { ClassConsensusV3__factory } from "./ClassConsensusV3__factory";
