/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ClassConsensus {
  export type StudentInfoStruct = { addr: AddressLike; name: string };

  export type StudentInfoStructOutput = [addr: string, name: string] & {
    addr: string;
    name: string;
  };

  export type PresentationDetailsStruct = {
    id: BigNumberish;
    category: string;
    studentName: string;
    studentAddr: AddressLike;
    timestamp: BigNumberish;
  };

  export type PresentationDetailsStructOutput = [
    id: bigint,
    category: string,
    studentName: string,
    studentAddr: string,
    timestamp: bigint
  ] & {
    id: bigint;
    category: string;
    studentName: string;
    studentAddr: string;
    timestamp: bigint;
  };
}

export interface ClassConsensusInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allPresentationIds"
      | "createPresentation"
      | "details"
      | "finalizeResult"
      | "getAllIDs"
      | "getAllStudents"
      | "getPresentationView"
      | "getUserRole"
      | "isRegistered"
      | "nextPresentationId"
      | "professor"
      | "professorOverride"
      | "registerStudent"
      | "registerTA"
      | "studentHistory"
      | "studentList"
      | "ta1"
      | "ta2"
      | "userNames"
      | "voteAsStudent"
      | "voteProfessor"
      | "voteTA"
      | "votes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PresentationCreated"
      | "ResultFinalized"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allPresentationIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPresentation",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "details",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeResult",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getAllIDs", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllStudents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPresentationView",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPresentationId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "professor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "professorOverride",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "registerStudent",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerTA",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "studentHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "studentList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ta1", values?: undefined): string;
  encodeFunctionData(functionFragment: "ta2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userNames",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voteAsStudent",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "voteProfessor",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "voteTA",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "votes", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "allPresentationIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPresentation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "details", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAllIDs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllStudents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPresentationView",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextPresentationId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "professor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "professorOverride",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registerTA", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "studentHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "studentList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ta1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ta2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userNames", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteAsStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteProfessor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voteTA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "votes", data: BytesLike): Result;
}

export namespace PresentationCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    studentName: string,
    category: string
  ];
  export type OutputTuple = [id: bigint, studentName: string, category: string];
  export interface OutputObject {
    id: bigint;
    studentName: string;
    category: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultFinalizedEvent {
  export type InputTuple = [id: BigNumberish, result: BigNumberish];
  export type OutputTuple = [id: bigint, result: bigint];
  export interface OutputObject {
    id: bigint;
    result: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [user: AddressLike, role: string, name: string];
  export type OutputTuple = [user: string, role: string, name: string];
  export interface OutputObject {
    user: string;
    role: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClassConsensus extends BaseContract {
  connect(runner?: ContractRunner | null): ClassConsensus;
  waitForDeployment(): Promise<this>;

  interface: ClassConsensusInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allPresentationIds: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  createPresentation: TypedContractMethod<
    [_category: string, _studentAddr: AddressLike],
    [void],
    "nonpayable"
  >;

  details: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        id: bigint;
        category: string;
        studentName: string;
        studentAddr: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  finalizeResult: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  getAllIDs: TypedContractMethod<[], [bigint[]], "view">;

  getAllStudents: TypedContractMethod<
    [],
    [ClassConsensus.StudentInfoStructOutput[]],
    "view"
  >;

  getPresentationView: TypedContractMethod<
    [id: BigNumberish],
    [
      [
        ClassConsensus.PresentationDetailsStructOutput,
        bigint,
        bigint,
        bigint
      ] & {
        detail: ClassConsensus.PresentationDetailsStructOutput;
        result: bigint;
        sPass: bigint;
        sFail: bigint;
      }
    ],
    "view"
  >;

  getUserRole: TypedContractMethod<
    [user: AddressLike],
    [
      [string, string, boolean] & {
        role: string;
        name: string;
        registered: boolean;
      }
    ],
    "view"
  >;

  isRegistered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  nextPresentationId: TypedContractMethod<[], [bigint], "view">;

  professor: TypedContractMethod<[], [string], "view">;

  professorOverride: TypedContractMethod<
    [id: BigNumberish, pass: boolean],
    [void],
    "nonpayable"
  >;

  registerStudent: TypedContractMethod<[_name: string], [void], "nonpayable">;

  registerTA: TypedContractMethod<
    [_name: string, _secretCode: string],
    [void],
    "nonpayable"
  >;

  studentHistory: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  studentList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  ta1: TypedContractMethod<[], [string], "view">;

  ta2: TypedContractMethod<[], [string], "view">;

  userNames: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  voteAsStudent: TypedContractMethod<
    [id: BigNumberish, pass: boolean],
    [void],
    "nonpayable"
  >;

  voteProfessor: TypedContractMethod<
    [id: BigNumberish, pass: boolean],
    [void],
    "nonpayable"
  >;

  voteTA: TypedContractMethod<
    [id: BigNumberish, pass: boolean],
    [void],
    "nonpayable"
  >;

  votes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint] & {
        prof: bigint;
        ta1: bigint;
        ta2: bigint;
        studentsBloc: bigint;
        exists: boolean;
        finalResult: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allPresentationIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "createPresentation"
  ): TypedContractMethod<
    [_category: string, _studentAddr: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "details"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint] & {
        id: bigint;
        category: string;
        studentName: string;
        studentAddr: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "finalizeResult"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllIDs"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getAllStudents"
  ): TypedContractMethod<
    [],
    [ClassConsensus.StudentInfoStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPresentationView"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [
        ClassConsensus.PresentationDetailsStructOutput,
        bigint,
        bigint,
        bigint
      ] & {
        detail: ClassConsensus.PresentationDetailsStructOutput;
        result: bigint;
        sPass: bigint;
        sFail: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserRole"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [string, string, boolean] & {
        role: string;
        name: string;
        registered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextPresentationId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "professor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "professorOverride"
  ): TypedContractMethod<
    [id: BigNumberish, pass: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerStudent"
  ): TypedContractMethod<[_name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerTA"
  ): TypedContractMethod<
    [_name: string, _secretCode: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "studentHistory"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "studentList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "ta1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ta2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userNames"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "voteAsStudent"
  ): TypedContractMethod<
    [id: BigNumberish, pass: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voteProfessor"
  ): TypedContractMethod<
    [id: BigNumberish, pass: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voteTA"
  ): TypedContractMethod<
    [id: BigNumberish, pass: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "votes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint] & {
        prof: bigint;
        ta1: bigint;
        ta2: bigint;
        studentsBloc: bigint;
        exists: boolean;
        finalResult: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "PresentationCreated"
  ): TypedContractEvent<
    PresentationCreatedEvent.InputTuple,
    PresentationCreatedEvent.OutputTuple,
    PresentationCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ResultFinalized"
  ): TypedContractEvent<
    ResultFinalizedEvent.InputTuple,
    ResultFinalizedEvent.OutputTuple,
    ResultFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "PresentationCreated(uint256,string,string)": TypedContractEvent<
      PresentationCreatedEvent.InputTuple,
      PresentationCreatedEvent.OutputTuple,
      PresentationCreatedEvent.OutputObject
    >;
    PresentationCreated: TypedContractEvent<
      PresentationCreatedEvent.InputTuple,
      PresentationCreatedEvent.OutputTuple,
      PresentationCreatedEvent.OutputObject
    >;

    "ResultFinalized(uint256,uint8)": TypedContractEvent<
      ResultFinalizedEvent.InputTuple,
      ResultFinalizedEvent.OutputTuple,
      ResultFinalizedEvent.OutputObject
    >;
    ResultFinalized: TypedContractEvent<
      ResultFinalizedEvent.InputTuple,
      ResultFinalizedEvent.OutputTuple,
      ResultFinalizedEvent.OutputObject
    >;

    "UserRegistered(address,string,string)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
